import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const toastOptions = {
  error: {
    style: {
      background: "#D8000C",
      color: "white",
    },
    iconTheme: {
      primary: "#ffffff",
      secondary: "#D8000C",
    },
  },
  success: {
    style: {
      background: "#4F8A10",
      color: "white",
    },
    iconTheme: {
      primary: "#ffffff",
      secondary: "#4F8A10",
    },
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body style={{ minHeight: "100vh" }} className={inter.className}>
        <Toaster
          position="bottom-right"
          toastOptions={toastOptions}
          reverseOrder={false}
        />
        {children}
      </body>
    </html>
  );
}
